pages: # задание должно быть именованными страницами
  image: node:latest
  stage: deploy
  script:
    - npm ci
    - npm install
    - npm run build
    - npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch
    - mv public public-vue
    - find dist -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - dist
  only:
    - master
